name: Build and Deploy Static Dashboard

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 1' # every Monday at 00:00 UTC
  workflow_dispatch:    # also allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install V
        run: |
          git clone --depth=1 https://github.com/vlang/v
          cd v
          make

      - name: Restore .env (if needed)
        run: |
          echo "GITHUB_TOKEN=${{ secrets.GH_TOKEN }}" > .env

      - name: Build static site
        run: |
          ./v/v run main.v
          mkdir site
          mv out/* site/

      - name: Upload artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site/
          retention-days: 1

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
